### PR TITLE
fix: large list performance

### PR DESCRIPTION
**Pull request by huntabyte**
Closes: #45 

This PR cleans up a few of the internals that would cause the page to crash if a large list was rendered. There is still a slight delay at the beginning of typing when trying to filter a large list that I haven't been able to solve just yet. Some of these things may be related to the DOM updates that have to occur.

I'd be thrilled if someone else could take a look into how we can make that seamless as well, but this is enough of an improvement to merge for the time being.

### CODE REVIEW

**Comment by FredrikAugust** [comment]
Hey! Any updates on this one? We're currently trying to render a list of ~500 elements, and it's currently hanging for a couple of seconds when we try to filter:)

**Comment by rogerfar** [comment]
Unfortunately we ran into the same issue, list with only 200 items takes about 2-3 seconds for the search to hang.

**Comment by MadeInPierre** [comment]
Hi! Just here to also say that my ~500 items list freezes the page with 100% CPU for ~5 seconds, unfortunately I don't have the skills to propose a fix myself. 

Has anyone found a temporary workaround ? Event setting `filter={() => 1}` to attempt to bypass the built-in search algorithm does not have any effect.

**Comment by rogerfar** [comment]
> Has anyone found a temporary workaround ? Event setting `filter={() => 1}` to attempt to bypass the built-in search algorithm does not have any effect.
I use customer filtering on the datasource which works perfect. 

```
$: search = '';
$: groups = dataSource.filter(m => m.filter((m) => m.name.includes(search)

<Command.Input placeholder="Search..." bind:value={search} />
...
{#each groups as group}
    <Command.Item value={group.groupId}>{group.name}</Command.Item>
{/each}
```

**Pull request merged**
